### PR TITLE
notify: Fix new tickets notification type.

### LINKED ISSUE #68: cannot unmarshal new tickets notification
dcrd is returning []string instead of map[string]string. This causes dcrrpcclient to throw an error: Received invalid new tickets notification: json: cannot unmarshal array into Go value of type map[string]string

### PR DESCRIPTION
**Pull request by jolan**
Closes #68.

### CODE REVIEW

File: notify.go [hunk 1]
```diff
@@ -801,28 +797,22 @@ func parseNewTicketsNtfnParams(params []json.RawMessage) (*chainhash.Hash,
 		return nil, 0, 0, nil, err
 	}
 
-	// Unmarshal fourth parameter as a map[hash]hash.
-	tickets := make(map[string]string)
+	// Unmarshal fourth parameter as a slice.
+	tickets := make([]string, 0)
```
Comment (jrick) [inline notify.go]: `var tickets []string`

File: notify.go [hunk 2]
```diff
@@ -801,28 +797,22 @@ func parseNewTicketsNtfnParams(params []json.RawMessage) (*chainhash.Hash,
...
-		numberHash, err := chainhash.NewHashFromStr(ticketNH)
+	for _, ticketHashStr := range tickets {
+		// Create and cache Hash from tx hash.
+		ticketHash, err := chainhash.NewHashFromStr(ticketHashStr)
 		if err != nil {
 			return nil, 0, 0, nil, err
 		}
 
-		t[*ticketSha] = *numberHash
+		t = append(t, ticketHash)
```
Comment (jrick) [inline notify.go]: This will start appending new hashes to a slice of a bunch of nil pointers.  Either need to assign t[i] or make the slice with 0 len.

File: notify.go (hunk 1 above)
Comment (jolan) [reply notify.go]: OK, changed.

File: notify.go (hunk 2 above)
Comment (jolan) [reply notify.go]: Derp, too much copy and paste, not enough thinking. Fixed.

**Comment by jolan** [comment]
OK fixed, tested, works.

**Review by jrick — APPROVED** [review]
